# show sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# log SQL bind parameters (Hibernate 6+)
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.org.hibernate.SQL=DEBUG

# logs pour notre package
logging.level.school.hei.tsinjo=DEBUG
